idf_component_register(
    SRCS
        "main.c"
        "hid_parser.c"
        "ups_driver.c"
        "hid_var_map.c"
        "apc_subdriver.c"
        "mge_subdriver.c"
        "belkin_subdriver.c"
        "cps_subdriver.c"
        "tripplite_subdriver.c"
        "powercom_subdriver.c"
        "powervar_subdriver.c"
        "salicru_subdriver.c"
        "delta_subdriver.c"
        "ever_subdriver.c"
        "arduino_subdriver.c"
        "idowell_subdriver.c"
        "legrand_subdriver.c"
        "openups_subdriver.c"
        "ecoflow_subdriver.c"
        "riello_usb.c"
        "nut_server.c"
        "nvs_config.c"
        "web_server.c"
        "mqtt_pub.c"
    INCLUDE_DIRS "."
    EMBED_TXTFILES
        "web/index.html"
        "web/config.html"
)
